name: prism_env
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - pip:
      - numpy==1.24.2
      - pandas==2.0.0
      - python-decouple==3.8
      - openai==0.27.8
      - backoff==2.2.1
      - openpyxl==3.1.2
      - yake==0.4.8
      - nltk==3.8.1
      - gensim==4.3.1
      - scikit-learn==1.3.0
      - xlsxwriter==3.1.2
      - streamlit==1.25.0